// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwsxbdawaroetboddxme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3c3hiZGF3YXJvZXRib2RkeG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTUxOTIsImV4cCI6MjA2MTY3MTE5Mn0.4On6lZ-KwJ1dLYuM9CDjgRTZegcbjXceUb0Bqrp9O08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);